name: Terraform Apply (Networking)

on:
  push:
    branches:
      - main
    paths:
      - "dev/**"

permissions:
  id-token: write
  contents: read

jobs:
  terraform_apply:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: dev

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ASSUME }}
          aws-region: ap-south-1

      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Terraform Init
        run: terraform init -input=false

      - name: Terraform Apply (VPC + Networking only)
        run: |
          terraform apply \
            -input=false \
            -auto-approve \
            -target=module.networking
