name: Terraform Plan

on:
  pull_request:
    branches:
      - main
    paths:
      - "dev/**"
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  terraform_plan:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: dev

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ASSUME }}
          aws-region: ap-south-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Terraform Init
        run: terraform init -input=false

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        id: plan
        run: |
          terraform plan -input=false -no-color > plan.txt
          echo "plan_result=changes" >> $GITHUB_OUTPUT

      - name: Comment Terraform Plan on PR
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');

            const planPath = 'dev/plan.txt';
            let plan = 'Plan output not available.';

            if (fs.existsSync(planPath)) {
              plan = fs.readFileSync(planPath, 'utf8');
            }

            const MAX_LENGTH = 65000;
            const truncated = plan.length > MAX_LENGTH;
            const visiblePlan = plan.slice(0, MAX_LENGTH);

            const body = `
            ## 🏗️ Terraform Plan (dev)

            **Triggered by:** @${context.actor}  
            **Commit:** \`${context.payload.pull_request.head.sha}\`  

            <details>
            <summary>📄 Show Terraform Plan</summary>

            \`\`\`hcl
            ${visiblePlan}
            \`\`\`
            ${truncated ? '\n⚠️ Output truncated due to GitHub comment limits.' : ''}
            </details>
            `;

            const { data: comments } = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
            });

            const existing = comments.find(c =>
              c.user.type === 'Bot' &&
              c.body.includes('Terraform Plan (dev)')
            );

            if (existing) {
              await github.rest.issues.updateComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                comment_id: existing.id,
                body,
              });
            } else {
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                body,
              });
            }
 
