- name: Comment Plan Results
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            const env = process.env.ENVIRONMENT;
            const planResult = '${{ steps.plan.outputs.plan_result }}';
            const planPath = `plan_output_${env}.txt`;

            let plan = 'Plan output not available.';
            let planStatus = '❌ Failed';

            switch(planResult) {
              case 'no_changes':
                planStatus = '✅ No Changes';
                break;
              case 'changes':
                planStatus = '📋 Changes Detected';
                break;
              case 'error':
                planStatus = '❌ Plan Failed';
                break;
            }

            if (fs.existsSync(planPath)) {
              plan = fs.readFileSync(planPath, 'utf8');
            }

            const comment = `
            ### 🏗️ Terraform Plan for \`${env}\` ${planStatus}

            **Plan Result:** ${planResult}  
            **Triggered by:** @${{ github.actor }}  
            **Commit:** \`${{ github.event.pull_request.head.sha }}\`  
            **Workflow:** [${{ github.run_id }}](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})

            <details><summary>📄 Show Plan Output (${plan.length} chars)</summary>

            \`\`\`hcl
            ${plan.slice(0, 65000)}
            \`\`\`
            ${plan.length > 65000 ? '\n⚠️ Output truncated. Download full plan from workflow artifacts.' : ''}
            </details>
            `;

            // Find existing comment to update
            const { data: comments } = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
            });

            const botComment = comments.find(comment => 
              comment.user.type === 'Bot' && 
              comment.body.includes(`Terraform Plan for \`${env}\``)
            );

            if (botComment) {
              await github.rest.issues.updateComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                comment_id: botComment.id,
                body: comment
              });
            } else {
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                body: comment
              });
            }
 
